# Generated by Django 5.2.4 on 2025-07-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_blog_post_postimage_delete_blogimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='nexaadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
