# Generated by Django 5.2.4 on 2025-07-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='nexaadmin',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nexaadmin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
    ]
